[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  ". /app/venv/bin/activate && pip install --upgrade pip",
  ". /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && python3 main.py"
